formation/urls.py
from django.urls import path
from formation.views import FormationList, OfficeList, InfographieList, ArtList, EnglishList, ProgrammationList

app_name = 'formation'
urlpatterns = [
    path('', FormationList.as_view(), name='formation-list'),
    path('office/', OfficeList.as_view(), name='office-list'),
    path('infographie/', InfographieList.as_view(), name='infographie-list'),
    path('art_culture/', ArtList.as_view(), name='art-list'),
    path('english/', EnglishList.as_view(), name='english-list'),
    path('programmation/', ProgrammationList.as_view(), name='programmation-list'),
]

ouragan_opp/urls.py
from django.contrib import admin
from django.urls import include ,path
from django.views.generic import TemplateView
from ouragan.views import ContactView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='pages/index.html'), name='home'),
    path('contact/', ContactView.as_view(template_name='pages/contact.html'), name='contact'),
    path('opportunites/', TemplateView.as_view(template_name='pages/opportunites.html'), name='opportunites'),
    path('opportunites/m', TemplateView.as_view(template_name='pages/m.html'), name='m'),
    path('opportunites/e', TemplateView.as_view(template_name='pages/e.html'), name='e'),
    path('opportunites/a', TemplateView.as_view(template_name='pages/a.html'), name='a'),
    path('team/', TemplateView.as_view(template_name='pages/team.html'), name='team'),
    path('eagle_pub/', TemplateView.as_view(template_name='pages/eagle_pub.html'), name='eagle_pub'),
    path('f/', include('formation.urls')),
]

formation/models.py
from django.db import models

# Create your models here.


class Formation(models.Model):
    title = models.CharField(max_length=150)
    body = models.TextField(max_length=800)

    def __str__(self):
        return self.title


class Art_Culture(models.Model):
    title_art = models.CharField(max_length=150)
    contenu_art = models.TextField(max_length=500)
    last_accessed = models.DateTimeField()

    def __str__(self):
        return self.title_art


class Office(models.Model):
    titre_office = models.CharField(max_length=150)
    contenu_office = models.TextField(max_length=500)
    last_accessed = models.DateTimeField()

    def __str__(self):
        return self.titre_office


class Infographie(models.Model):
    title_info = models.CharField(max_length=150)
    contenu_info = models.TextField(max_length=500)
    last_accessed = models.DateTimeField()

    def __str__(self):
        return self.title_info


class English(models.Model):
    title_english = models.CharField(max_length=150)
    contenu_english = models.TextField(max_length=500)
    last_accessed = models.DateTimeField()

    def __str__(self):
        return self.title_english


class Programmation(models.Model):
    title_Programmation = models.CharField(max_length=150)
    contenu_Programmation = models.TextField(max_length=500)
    last_accessed = models.DateTimeField()

    def __str__(self):
        return self.title_Programmation

ouragan/models.py
from django.db import models

# Create your models here.

ouragan/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

    def send_email(self):
        # send email using the self.cleaned_data dictionary
        envoyeur = forms.EmailField(label="Votre adresse mail")
        renvoi = forms.BooleanField(help_text="Cochez si vous souhaitez obtenir une copie du mail envoyé.", required=False)
        return envoyeur, renvoi

formation/views.py
from django.shortcuts import render

# from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from formation.models import Formation, Office, Infographie, English, Art_Culture, Programmation


# Create your views here.


class FormationList(ListView):
    # model = Formation
    context_object_name = 'formation'
    queryset = Formation.objects.all()

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['formation_list'] = Formation.objects.all()
        return context


class OfficeList(ListView):
    # model = Formation
    context_object_name = 'formation'
    queryset = Office.objects.all()

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['office_list'] = Office.objects.all()
        return context


class InfographieList(ListView):
    # model = Formation
    context_object_name = 'formation'
    # template_name = 'formation/infographie_list.html'
    queryset = Infographie.objects.all()

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['infographie_list'] = Infographie.objects.all()
        return context


class ArtList(ListView):
    # model = Formation
    context_object_name = 'formation'
    queryset = Art_Culture.objects.all()

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['art_culture_list'] = Art_Culture.objects.all()
        return context


class EnglishList(ListView):
    # model = Formation
    context_object_name = 'formation'
    queryset = English.objects.all()

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['art_culture_list'] = English.objects.all()
        return context


class ProgrammationList(ListView):
    # model = Formation
    context_object_name = 'formation'
    queryset = Programmation.objects.all()

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['entrepeneuriat_list'] = Programmation.objects.all()
        return context


# class FormationDetail(DetailView):
#
#     queryset = Formation.objects.all
#
#     def get_object(self, queryset=None):
#         # Call the superclass
#         object = super().get_object()
#         # Record the last accessed date
#         object.last_accessed = timezone.now()
#         object.save()
#         # Return the object
#         return object

ouragan/views.py
from django.shortcuts import render
from .forms import ContactForm
from django.views.generic.edit import FormView
# Create your views here.

class ContactView(FormView):
    template_name = 'contact.html'
    form_class = ContactForm
    success_url = '/thanks/'

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        form.send_email()
        return super().form_valid(form)


def bootstrap(request):
    return render(request, 'bootstrap/__boot.html')

templates/formation/english_list.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load staticfiles %}
<title>{% block title %}Formations | {{ block.super }}{% endblock %}</title>


{% block content %}
    <!--==========================
      Services Section
    ============================-->
    <section id="services">
      <div class="container">

        <header class="section-header wow fadeInUp">
          <h3>Anglais</h3>
          <p>Nous formons en beaucoup de domaine et nos formations sont aussi disponible a domicile grace a une equipe competante disponible que pour vous.</p>
        </header>

        <div class="row">
          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-barcode-outline"></i></div>
              {% for obj in object_list %}
                  <h4 class="title">{{ obj.title_english}}</h4>
                  <p class="description">{{ obj.contenu_english }} <br/> {{ obj.last_accessed  }}</p>
              {% endfor %}
          </div>
        <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-barcode-outline"></i></div>
              {% for obj in object_list %}
                  <h4 class="title">{{ obj.title_english}}</h4>
                  <p class="description">{{ obj.contenu_english }} <br/> {{ obj.last_accessed  }}</p>
              {% endfor %}
          </div>
        <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-barcode-outline"></i></div>
              {% for obj in object_list %}
                  <h4 class="title">{{ obj.title_english}}</h4>
                  <p class="description">{{ obj.contenu_english }} <br/> {{ obj.last_accessed  }}</p>
              {% endfor %}
          </div>

        </div>

      </div>
    </section><!-- #services -->


{% endblock %}

templates/formation/formation_list.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load staticfiles %}
<title>{% block title %}Formations | {{ block.super }}{% endblock %}</title>

{% block content %}
     <!--==========================
      Services Section
    ============================-->
    <section id="services" class="section-bg">
      <div class="container">

        <header class="section-header wow fadeInUp">
          <h3>Formations</h3>
          <p>OURAGAN ouvre ses portes à toutes personnes ayant des ambitions de se perfectionnée dans le domaine que vous trouverez ci-dessous en vous offrant de formations pratiques avec des méthodes efficaces. Doter d’un personnel qualifié, nous dispensons des cours en ligne et nous mettons les combles à notre savoir-faire afin de répondre à vos besoins.</p>
        </header>

        <div class="row">

          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-analytics-outline"></i></div>
            <h4 class="title"><a href="#">Office</a></h4>
            <p class="description"></p>
          </div>
          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-bookmarks-outline"></i></div>
            <h4 class="title"><a href="#">Infographie</a></h4>
            <p class="description"></p>
          </div>
          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-paper-outline"></i></div>
            <h4 class="title"><a href="#">Art et Culture</a></h4>
            <p class="description"></p>
          </div>
          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-speedometer-outline"></i></div>
            <h4 class="title"><a href="#">Langues</a></h4>
              <p class="description"></p>
          </div>
<!--{#          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">#}-->
<!--{#            <div class="icon"><i class="ion-ios-barcode-outline"></i></div>#}-->
<!--{#            <h4 class="title"><a href="{% url 'formation:marketing-list' %}">Marketing et Management</a></h4>#}-->
<!--{#            <p class="description">Nous formons en beaucoup de domaine et nos formations sont aussi disponible a domicile grace a une equipe competante disponible que pour vous.</p>#}-->
<!--{#          </div>#}-->
<!--{#          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">#}-->
<!--{#            <div class="icon"><i class="ion-ios-people-outline"></i></div>#}-->
<!--{#            <h4 class="title"><a href="{% url 'formation:entrepeneuriat-list' %}">Entrepeneuriat</a></h4>#}-->
<!--{#            <p class="description">ENous formons en beaucoup de domaine et nos formations sont aussi disponible a domicile grace a une equipe competante disponible que pour vous.</p>#}-->
<!--{#          </div>#}-->
<!--{##}-->
<!--{#            <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">#}-->
<!--{#            <div class="icon"><i class="ion-ios-people-outline"></i></div>#}-->
<!--{#            <h4 class="title"><a href="{% url 'formation:programmation-list' %}">Language de Programmation</a></h4>#}-->
<!--{#            <p class="description">Nous formons en beaucoup de domaine et nos formations sont aussi disponible a domicile grace a une equipe competante disponible que pour vous.</p>#}-->
<!--{#          </div>#}-->
<!--{#            <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">#}-->
<!--{#            <div class="icon"><i class="ion-ios-people-outline"></i></div>#}-->
<!--{#            <h4 class="title"><a href="">LeaderShips</a></h4>#}-->
<!--{#            <p class="description">Nous formons en beaucoup de domaine et nos formations sont aussi disponible a domicile grace a une equipe competante disponible que pour vous.</p>#}-->
<!--{#          </div>#}-->

        </div>

      </div>
    </section><!-- #services -->

{% endblock %}

templates/formation/infographie_list.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load staticfiles %}
<title>{% block title %}Formations | {{ block.super }}{% endblock %}</title>

{% block content %}
    <!--==========================
      Services Section
    ============================-->
    <section id="services">
      <div class="container">

        <header class="section-header wow fadeInUp">
          <h3>Infographie</h3>
          <p>Nous formons en beaucoup de domaine et nos formations sont aussi disponible a domicile grace a une equipe competante disponible que pour vous.</p>
        </header>

        <div class="row">
          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-barcode-outline"></i></div>
              {% for obj in object_list %}
                  <h4 class="title">{{ obj.title_info}}</h4>
                  <p class="description">{{ obj.contenu_info }}<br/> {{ obj.last_accessed  }}</p>
              {% endfor %}
          </div>
        <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-barcode-outline"></i></div>
              {% for obj in object_list %}
                  <h4 class="title">{{ obj.title_info}}</h4>
                  <p class="description">{{ obj.contenu_info }}<br/> {{ obj.last_accessed  }}</p>
              {% endfor %}
          </div>
        <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-barcode-outline"></i></div>
              {% for obj in object_list %}
                  <h4 class="title">{{ obj.title_info}}</h4>
                  <p class="description">{{ obj.contenu_info }}<br/> {{ obj.last_accessed  }}</p>
              {% endfor %}
          </div>

        </div>

      </div>
    </section><!-- #services -->

{% endblock %}

templates/formation/office_list.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load staticfiles %}
<title>{% block title %}Formations | {{ block.super }}{% endblock %}</title>


{% block content %}

    <section id="services">
      <div class="container">

        <header class="section-header wow fadeInUp">
          <h3>Bureautique</h3>
          <p>Nous formons en beaucoup de domaine et nos formations sont aussi disponible a domicile grace a une equipe competante disponible que pour vous.</p>
        </header>

        <div class="row">
          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-barcode-outline"></i></div>
              {% for obj in object_list %}
                  <h4 class="title">{{ obj.titre_office }}</h4>
                  <p class="description">{{ obj.contenu_office }} <br/> {{ obj.last_accessed  }}</p>
              {% endfor %}
          </div>
        <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-barcode-outline"></i></div>
              {% for obj in object_list %}
                  <h4 class="title">{{ obj.titre_office }}</h4>
                  <p class="description">{{ obj.contenu_office }} <br/> {{ obj.last_accessed  }}</p>
              {% endfor %}
          </div>
        <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-barcode-outline"></i></div>
              {% for obj in object_list %}
                  <h4 class="title">{{ obj.titre_office }}</h4>
                  <p class="description">{{ obj.contenu_office }} <br/> {{ obj.last_accessed  }}</p>
              {% endfor %}
          </div>
        </div>

      </div>
    </section><!-- #services -->

{% endblock %}

templates/formation/programmation_list.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load staticfiles %}
<title>{% block title %}Formations | {{ block.super }}{% endblock %}</title>


{% block content %}

    <section id="services">
      <div class="container">

        <header class="section-header wow fadeInUp">
          <h3>Programmation</h3>
          <p>Nous formons en beaucoup de domaine et nos formations sont aussi disponible a domicile grace a une equipe competante disponible que pour vous.</p>
        </header>

        <div class="row">
          <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-barcode-outline"></i></div>
              {% for obj in object_list %}
                  <h4 class="title">{{ obj.title_Programmation }}</h4>
                  <p class="description">{{ obj.contenu_Programmation }} <br/> {{ obj.last_accessed  }}</p>
              {% endfor %}
          </div>
        <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-barcode-outline"></i></div>
              {% for obj in object_list %}
                  <h4 class="title">{{ obj.title_Programmation }}</h4>
                  <p class="description">{{ obj.contenu_Programmation }} <br/> {{ obj.last_accessed  }}</p>
              {% endfor %}
          </div>
        <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="icon"><i class="ion-ios-barcode-outline"></i></div>
              {% for obj in object_list %}
                  <h4 class="title">{{ obj.title_Programmation }}</h4>
                  <p class="description">{{ obj.contenu_Programmation }} <br/> {{ obj.last_accessed  }}</p>
              {% endfor %}
          </div>
        </div>

      </div>
    </section><!-- #services -->

{% endblock %}

templates/layouts/_footer.html
{% load static %}


<section id="clients" class="wow fadeInUp">
       <div class="container">

          <div class="owl-carousel clients-carousel">
                      <img src="../../static/images/clients/client-1.png" alt="">
                      <img src="../../static/images/clients/client-2.png" alt="">
                      <img src="../../static/images/clients/client-3.png" width="300" height="70" alt="">
                     <!--<img src="../../static/images/clients/client-4.jpg" alt="">-->
                      <!--<img src="../../static/images/clients/client-5.png" width="300" height="70" alt="">-->
                     <!--<img src="../../static/images/clients/client-6.png" alt="">-->
                      <!--<img src="../../static/images/clients/client-7.png" alt="">-->
                      <!--<img src="../../static/images/clients/client-8.png" alt="">-->
           </div>

        </div>
 </section><!-- #clients -->


 <!--==========================
    Footer
  ============================-->
  <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Menu</h4>
            <ul>
              <li><i class="ion-ios-arrow-right"></i> <a href="{% url 'home' %}">Accueil</a></li>
              <li><i class="ion-ios-arrow-right"></i> <a href="{% url 'formation:formation-list' %}">Formations</a></li>
              <li><i class="ion-ios-arrow-right"></i> <a href="#">Secteurs</a></li>
              <li><i class="ion-ios-arrow-right"></i> <a href="{% url 'opportunites' %}">Opportunités</a></li>
              <li><i class="ion-ios-arrow-right"></i> <a href="{% url 'team' %}">Team</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-contact">
            <h4>Suivez-Nous</h4>

            <div class="social-links">
              <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
              <a href="#" class="instagram"><i class="fa fa-instagram"></i></a>
              <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
              <a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a>
              <a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a>
            </div>

          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright {% now 'Y' %} &middot; <strong>Ouragan</strong> &middot; All Rights Reserved
      </div>
    </div>
  </footer><!-- #footer -->

  <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

templates/layouts/_nav.html
{% load static %}

 <!--==========================
    Header
  ============================-->
  <header id="header">
    <div class="container-fluid">

           <div id="logo" class="pull-left">
            <!-- Uncomment below if you prefer to use an image logo -->
            <a href="{% url 'home' %}"><img src="../../static/images/titre.png" alt=""/></a>
          </div>
      </div>

      <nav id="nav-menu-container">
        <ul class="nav-menu">
          <li class="menu-active"><a href="{% url 'home' %}">Accueil</a></li>
          <li><a href="{% url 'opportunites' %}">Opportunités</a></li>
          <li><a href="{% url 'formation:formation-list' %}">Formations</a></li>
          <li><a href="#">Eagle_pub</a></li>
          <li><a href="{% url 'contact' %}">Contact</a></li>
          <!--<li><a href="#">About</a></li>-->
        </ul>
      </nav><!-- #nav-menu-container -->
  </header><!-- #header -->

templates/layouts/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Ouragan</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">

  <!-- Favicons -->
  <link href="../../static/images/favicon.png" rel="icon">
  <link href="../../static/images/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Montserrat:300,400,500,700" rel="stylesheet">

  <!-- Bootstrap CSS File -->
  <link href="../../static/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Libraries CSS Files -->
  <link href="../../static/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet">
  <link href="../../static/lib/animate/animate.min.css" rel="stylesheet">
  <link href="../../static/lib/ionicons/css/ionicons.min.css" rel="stylesheet">
  <link href="../../static/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
  <link href="../../static/lib/lightbox/css/lightbox.min.css" rel="stylesheet">

  <!-- Main Stylesheet File -->
  <link href="../../static/css/style.css" rel="stylesheet">

  <!-- =======================================================
    Theme Name: BizPage
    Theme URL: https://bootstrapmade.com/bizpage-bootstrap-business-template/
    Author: BootstrapMade.com
    License: https://bootstrapmade.com/license/
  ======================================================= -->
</head>
<body>
{% include 'layouts/_nav.html' %}

{% block content %}{% endblock %}

{% include 'layouts/_footer.html' %}

  <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

  <!-- JavaScript Libraries -->
  <script src="../../static/lib/jquery/jquery.min.js"></script>
  <script src="../../static/lib/jquery/jquery-migrate.min.js"></script>
  <script src="../../static/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="../../static/lib/easing/easing.min.js"></script>
  <script src="../../static/lib/superfish/hoverIntent.js"></script>
  <script src="../../static/lib/superfish/superfish.min.js"></script>
  <script src="../../static/lib/wow/wow.min.js"></script>
  <script src="../../static/lib/waypoints/waypoints.min.js"></script>
  <script src="../../static/lib/counterup/counterup.min.js"></script>
  <script src="../../static/lib/owlcarousel/owl.carousel.min.js"></script>
  <script src="../../static/lib/isotope/isotope.pkgd.min.js"></script>
  <script src="../../static/lib/lightbox/js/lightbox.min.js"></script>
  <script src="../../static/lib/touchSwipe/jquery.touchSwipe.min.js"></script>
  <!-- Contact Form JavaScript File -->
  <script src="../../static/contactform/contactform.js"></script>

  <!-- Template Main Javascript File -->
  <script src="../../static/js/main.js"></script>
</body>
</html>

templates/pages/a.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load staticfiles %}
<title>{% block title %}Miniers | {{ block.super }}{% endblock %}</title>

{% block content %}
    <section id="portfolio"  class="section-bg" >
      <div class="container">

        <header class="section-header">
              <h3 class="section-title">SECTEUR AGRICOLE</h3>
         </header>

          <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <img class="d-block w-100" src="../../static/images/intro-carousel/1.jpg" height="400" width="800" alt="First slide">
                </div>
                <div class="carousel-item">
                  <img class="d-block w-100" src="../../static/images/intro-carousel/2.jpg" height="400" width="800" alt="Second slide">
                </div>
                <div class="carousel-item">
                  <img class="d-block w-100" src="../../static/images/intro-carousel/5.jpg" height="400" width="800" alt="Third slide">
                </div>
              </div>
            </div>
          <hr/>
        <p class="text-justify">La République Démocratie Congo est doté des possibilités immenses dans le domaine de l’agriculture susceptible d’en faire un grand grenier pour l’Afrique et une partie du monde. Il n’existe pas un recoin quelconque dans ce pays où il manque une ressource agricole.
            <br/>Le sol de la RDC étant très fertile et procure une végétation dense de plusieurs espèces animales, longtemps négligé et vierge, son secteur agricole est en voie de développement. OURAGAN saisie cette occasion d’offrir dans le cadre de l’agro-business l’opportunité à ses clients investisseurs un partenariat industriel et semi-industriel.</p>

      </div>
    </section>
{% endblock %}

templates/pages/eagle_pub.html
<h1>Eagle_pub</h1>

templates/pages/team.html
<h1>Team</h1>